### ISSUE TITLE
我在安装置顶工具以后，弹出的窗口左上方的三个按钮错位，鼠标需要在按钮显示的下方点击才有效。

### ISSUE THREAD

**Issue by Zju-Qibowen** [harytfw/popup-tool#12]

**Comment by harytfw** [comment]
v67的时候就有这个情况了
我以为只是我个人的问题，现在我可以确定是浏览器自己的问题
见：https://bugzilla.mozilla.org/show_bug.cgi?id=1563831
等mozilla修复就可以了
