### ISSUE TITLE
B站不显示弹出按钮

### ISSUE THREAD

**Issue by 0x04c11db7** [harytfw/popup-tool#2]
其它网站正常

**Comment by harytfw** [comment]
请提供具体的链接。有截图描述的话更好。

**Comment by 0x04c11db7** [comment]
Firefox 65.0.2(64位)
[直播](https://live.bilibili.com/6)
![default](https://user-images.githubusercontent.com/25258169/53694333-46244580-3de8-11e9-946b-e447b14a668c.png)
