### ISSUE TITLE
火狐浏览器按照步骤做还是无法置顶弹出视频窗口。

### ISSUE THREAD

**Issue by nayuurin** [harytfw/popup-tool#4]
powershell打开【add-to-registry.ps1】文件显示【无法加载文件，因为在此系统中禁止执行脚本】
WIN7 64位
火狐浏览器6603版本。

**Comment by harytfw** [comment]
这是我的疏忽，没有描述清楚安装步骤。我重新更新了文档，你可以参考：https://github.com/harytfw/popup-tool
