### ISSUE TITLE
火猫直播 h5模式失效了

### ISSUE THREAD

**Issue by smzh369** [harytfw/popup-tool#5]
rt，flash没问题

**Comment by harytfw** [comment]
现在火猫要开启h5模式需要修改UA（比如改UA为chrome）
这个没办法用我这个扩展解决。

**Comment by smzh369** [comment]
> 
> 
> 现在火猫要开启h5模式需要修改UA（比如改UA为chrome）
> 这个没办法用我这个扩展解决。

我的意思是，切换成h5后扩展会失效。

**Comment by harytfw** [comment]
我测试的情况：
首先，我用 User-Agent Switcher 切换UA为 Windows / Chrome
打开火猫直播，切换为h5模式，刷新页面，点击“弹出”可以创建窗口。

测试中出现的情况：
我用火狐 66 测试的时候会出现一点问题（直播有时候会暂停）但是弹出窗口可以创建
用火狐 67 开发者版会出现上面的问题，同时我发现在弹出窗口里鼠标位置会有错位（这应该是firefox自己的bug）

----
那么我想问的是：
1. 你的火狐的UserAgent是 什么？（打开 about:support 可获取，我可以从UA知道你的火狐版本，操作系统版本）
2. 扩展失效具体是什么情况？如 工具栏无法显示、工具栏可以显示但按“弹出”的话无窗口弹出、还是 其他
3. 有没有尝试过排除是扩展冲突的原因？

**Comment by smzh369** [comment]
> 
> 
> 我测试的情况：
> 首先，我用 User-Agent Switcher 切换UA为 Windows / Chrome
> 打开火猫直播，切换为h5模式，刷新页面，点击“弹出”可以创建窗口。
> 
> 测试中出现的情况：
> 我用火狐 66 测试的时候会出现一点问题（直播有时候会暂停）但是弹出窗口可以创建
> 用火狐 67 开发者版会出现上面的问题，同时我发现在弹出窗口里鼠标位置会有错位（这应该是firefox自己的bug）
> 
> 那么我想问的是：
> 
>     1. 你的火狐的UserAgent是 什么？（打开 about:support 可获取，我可以从UA知道你的火狐版本，操作系统版本）
> 
>     2. 扩展失效具体是什么情况？如 工具栏无法显示、工具栏可以显示但按“弹出”的话无窗口弹出、还是 其他
> 
>     3. 有没有尝试过排除是扩展冲突的原因？

1.我的ua是Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
实际中不需要切换ua，只需要在url后加上?h5player的查询参数就可以切换到h5，用header editor的重定向就可解决

2.我又看了一下，普通直播房间是正常的，但在赛事专题页面（url为https://www.huomao.com/zt/...）不能显示弹出按钮，如 http://www.huomao.com/zt/2019EPICENTER.html?room_number=695921#h5player 这个页面，应该不是扩展冲突的问题，专题直播房间和普通房间的html结构有点区别。

**Comment by harytfw** [comment]
如果只是这样子的话，我的解决方法就是增加一条规则适配 赛事专题页面

你手动重新下载最新版本就可以了：https://addons.mozilla.org/en-US/firefox/addon/popup-tool/

注意，我测试火狐v67的时候弹出窗口出现了问题，以后你更新火狐的时候要留意。

**Comment by smzh369** [comment]
好的，多谢发自我的华为手机-------- 原始邮件 --------主题：Re: [harytfw/popup-tool] 火猫直播 h5模式失效了 (#5)发件人：Haryfw 收件人：harytfw/popup-tool 抄送：smzh369 ,Author 如果只是这样子的话，我的解决方法就是增加一条规则适配 赛事专题页面

你手动重新下载最新版本就可以了：https://addons.mozilla.org/en-US/firefox/addon/popup-tool/

注意，我测试火狐v67的时候弹出窗口出现了问题，以后你更新火狐的时候要留意。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/harytfw/popup-tool/issues/5?email_source=notifications\u0026email_token=ADNFIM2O5GWGX7HV27UVVDDPWKCKVA5CNFSM4HNRRU6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVYP6BA#issuecomment-493944580",

"url": "https://github.com/harytfw/popup-tool/issues/5?email_source=notifications\u0026email_token=ADNFIM2O5GWGX7HV27UVVDDPWKCKVA5CNFSM4HNRRU6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVYP6BA#issuecomment-493944580",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
