### ISSUE TITLE
斗鱼直播不能弹出（且手动弹出有bug）

### ISSUE THREAD

**Issue by SunBig** [harytfw/popup-tool#9]
首页的视频能正常弹出。但是进入具体直播间后，不显示弹出按钮：

使用手动弹出，有时候不会检测到视频源，直接弹出整个页面，有时候能检测出视频源，但是视频会错位显示：
![图片](https://user-images.githubusercontent.com/27340676/58759333-d3e40e00-855a-11e9-90bb-19d8c5da93c8.png)

**Comment by SunBig** [comment]
更正一下，应该是像lpl比赛等活动页面的直播间弹出有问题，其他普通的直播间没问题

**Comment by harytfw** [comment]
不能显示弹出工具栏是扩展没有捕获到视频元素的问题，这个问题扩展目前不能完美解决，以后会想办法。

位置错误的问题会修复
